### ISSUE TITLE
File issue in analyse

### ISSUE THREAD

**Issue by djf604** [richard-meier/digit-trl#2]
Hi,

When I attempt to run an `analyse` using a similar form to that of the documentation:
```
$ java -jar digit.jar analyse -i ERR000524_PE.small.namesorted.sam \
-o test_output_analyse/ -r genomefile.idx.ChrLen.txt -s 2.33 -a false
```

I immediately get the following error:
```
Exception in thread "main" java.lang.NullPointerException
	at java.io.File.<init>(File.java:277)
	at main.Main.main(Unknown Source)
```

I'm not a java expert by any means, but it seems the software isn't able to properly instantiate the `File` object? I'm very certain that the paths are correct, for what it's worth.

Thanks for your help,
Dominic

**Comment by richard-meier** [comment]
Hello,

First of all, I apologize for the late response. I somehow completely missed this notification.

The error message suggests that a required file is not initialized properly. Based on your code I would expect this to be the low complexity annotation file, because you are not providing one. I would try to create an empty txt file, maybe called "empty.txt" and to run the following:

java -jar digit.jar analyse -i ERR000524_PE.small.namesorted.sam -o test_output_analyse/ -r genomefile.idx.ChrLen.txt -s 2.33 -a false -lc empty.txt

As a side note: It is difficult to judge what the exact problem is, when the stack trace is reported in the "(Unknown Source)" form. This suggests that you might have installed JRE but not JDK. For debugging purposes running the program after installing JDK is more useful to me, because when an error occurs the error message and stack trace will point to the exact position in the code where the error occured. So if errors persist I would encourage you to install JDK and report the  more detailed error message.

I hope this helps,

Richard
